In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import numpy as np
import pickle

In [2]:
data = pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
data =data.drop(['Surname','CustomerId','RowNumber'], axis=1).reset_index(drop=True)

data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [6]:
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])
data.head(10)

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
5,645,Spain,1,44,8,113755.78,2,1,0,149756.71,1
6,822,France,1,50,7,0.00,2,1,1,10062.80,0
7,376,Germany,0,29,4,115046.74,4,1,0,119346.88,1
8,501,France,1,44,4,142051.07,2,0,1,74940.50,0
9,684,France,1,27,2,134603.88,1,1,1,71725.73,0

In [7]:
onehot_encoder_geo = OneHotEncoder()
geo_encoder= onehot_encoder_geo.fit_transform(data[['Geography']])

geo_encoded_df = pd.DataFrame(geo_encoder.toarray(), columns=onehot_encoder_geo.get_feature_names_out(["Geography"]))

geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [8]:
data = pd.concat([data.drop('Geography',axis=1),geo_encoded_df], axis=1)
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [9]:
X = data.drop('EstimatedSalary',axis=1)
y = data['EstimatedSalary']

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [12]:
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('onehot_encoder_geo.pkl','wb') as file:
    pickle.dump(onehot_encoder_geo,file)

with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

# ANN implementation

In [13]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

model = Sequential([

        Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
        Dense(32, activation='relu'),
        Dense(1)
]
)

model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

c:\Users\arjun\Documents\Lang_chain_learning\DeepLearning\ANN model\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [14]:
log_dir = 'regressionlogs/fit/' + datetime.datetime.now().strftime('%Y%m%d-%H%M%S')
tensorflow_callback = TensorBoard(log_dir = str(log_dir), histogram_freq=1)
early_stopping_callback = EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [15]:
history = model.fit(
    X_train,y_train,validation_data=(X_test,y_test),epochs=100,
    callbacks=[tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 100379.5312 - mae: 100379.5312 - val_loss: 98526.3672 - val_mae: 98526.3672
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 99680.8672 - mae: 99680.8672 - val_loss: 97121.4297 - val_mae: 97121.4297
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 97249.6953 - mae: 97249.6953 - val_loss: 93550.2734 - val_mae: 93550.2734
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 92475.6094 - mae: 92475.6094 - val_loss: 87563.7500 - val_mae: 87563.7500
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 85449.0469 - mae: 85449.0469 - val_loss: 79668.0938 - val_mae: 79668.0938
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 76909.1406 - mae: 76909.1406 - val_loss: 71152.6719 - val_mae: 71152.6719
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 68288.2109 - mae: 68288.2109 - val_loss: 63425.2734 - val_mae: 63425.2734
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 60960.2773 - mae: 60960.2773 - val_loss: 57450.5859 - val_mae: 57450.5859
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 55878.3984 - mae: 55878.3984 - val_loss: 53745.4883 - val_mae: 53745.4883
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 52899.4258 - mae: 52899.4258 - val_loss: 51814.7578 - val_mae: 51814.7578
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51334.0898 - mae: 51334.0898 - val_loss: 51036.3164 - val_mae: 51036.3164
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50694.1875 - mae: 50694.1875 - val_loss: 50777.9258 - val_mae: 50777.9258
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50420.4453 - mae: 50420.4453 - val_loss: 50664.3750 - val_mae: 50664.3750
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50286.9570 - mae: 50286.9570 - val_loss: 50608.6211 - val_mae: 50608.6211
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50202.5547 - mae: 50202.5547 - val_loss: 50566.3711 - val_mae: 50566.3711
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50139.2227 - mae: 50139.2227 - val_loss: 50531.8633 - val_mae: 50531.8633
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50089.2812 - mae: 50089.2812 - val_loss: 50502.6836 - val_mae: 50502.6836
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50046.6016 - mae: 50046.6016 - val_loss: 50477.2070 - val_mae: 50477.2070
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50010.2734 - mae: 50010.2734 - val_loss: 50453.8281 - val_mae: 50453.8281
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49977.1250 - mae: 49977.1250 - val_loss: 50425.5312 - val_mae: 50425.5312
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49942.4609 - mae: 49942.4609 - val_loss: 50415.9102 - val_mae: 50415.9102
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49912.1250 - mae: 49912.1250 - val_loss: 50407.8086 - val_mae: 50407.8086
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49883.7930 - mae: 49883.7930 - val_loss: 50385.6719 - val_mae: 50385.6719
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49859.5391 - mae: 49859.5391 - val_loss: 50372.4141 - val_mae: 50372.4141
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49837.3555 - mae: 49837.3555 - val_loss: 50370.9492 - val_mae: 50370.9492
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49813.9883 - mae: 49813.9883 - val_loss: 50352.3242 - val_mae: 50352.3242
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49794.2227 - mae: 49794.2227 - val_loss: 50345.1289 - val_mae: 50345.1289
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49769.2383 - mae: 49769.2383 - val_loss: 50342.8750 - val_mae: 50342.8750
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49751.0156 - mae: 49751.0156 - val_loss: 50328.4375 - val_mae: 50328.4375
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49733.9609 - mae: 49733.9609 - val_loss: 50324.3125 - val_mae: 50324.3125
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49716.6484 - mae: 49716.6484 - val_loss: 50312.5234 - val_mae: 50312.5234
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49700.4102 - mae: 49700.4102 - val_loss: 50315.7930 - val_mae: 50315.7930
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49683.5352 - mae: 49683.5352 - val_loss: 50305.4844 - val_mae: 50305.4844
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49671.7109 - mae: 49671.7109 - val_loss: 50301.5703 - val_mae: 50301.5703
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49655.8672 - mae: 49655.8672 - val_loss: 50301.0234 - val_mae: 50301.0234
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49645.2969 - mae: 49645.2969 - val_loss: 50288.4805 - val_mae: 50288.4805
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49632.0039 - mae: 49632.0039 - val_loss: 50290.4531 - val_mae: 50290.4531
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49621.8398 - mae: 49621.8398 - val_loss: 50285.2422 - val_mae: 50285.2422
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49609.0977 - mae: 49609.0977 - val_loss: 50280.6562 - val_mae: 50280.6562
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49599.2734 - mae: 49599.2734 - val_loss: 50272.5898 - val_mae: 50272.5898
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49589.0703 - mae: 49589.0703 - val_loss: 50269.3047 - val_mae: 50269.3047
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49577.2930 - mae: 49577.2930 - val_loss: 50270.8164 - val_mae: 50270.8164
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49570.5234 - mae: 49570.5234 - val_loss: 50266.0703 - val_mae: 50266.0703
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49565.8320 - mae: 49565.8320 - val_loss: 50249.7852 - val_mae: 50249.7852
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49553.0664 - mae: 49553.0664 - val_loss: 50256.5312 - val_mae: 50256.5312
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49545.5781 - mae: 49545.5781 - val_loss: 50258.6367 - val_mae: 50258.6367
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49534.5469 - mae: 49534.5469 - val_loss: 50251.9883 - val_mae: 50251.9883
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49527.6094 - mae: 49527.6094 - val_loss: 50247.4727 - val_mae: 50247.4727
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49518.0898 - mae: 49518.0898 - val_loss: 50236.9492 - val_mae: 50236.9492
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49513.1367 - mae: 49513.1367 - val_loss: 50241.8164 - val_mae: 50241.8164
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49506.1641 - mae: 49506.1641 - val_loss: 50253.6562 - val_mae: 50253.6562
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49497.7422 - mae: 49497.7422 - val_loss: 50244.4375 - val_mae: 50244.4375
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49489.4062 - mae: 49489.4062 - val_loss: 50255.2578 - val_mae: 50255.2578
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49481.9453 - mae: 49481.9453 - val_loss: 50243.4375 - val_mae: 50243.4375
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49475.4531 - mae: 49475.4531 - val_loss: 50245.1758 - val_mae: 50245.1758
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49469.7891 - mae: 49469.7891 - val_loss: 50243.0273 - val_mae: 50243.0273
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49465.2266 - mae: 49465.2266 - val_loss: 50237.3750 - val_mae: 50237.3750
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49458.9297 - mae: 49458.9297 - val_loss: 50241.7773 - val_mae: 50241.7773
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49451.1367 - mae: 49451.1367 - val_loss: 50240.4258 - val_mae: 50240.4258

In [ ]:
%load_ext tensorboard

In [22]:
%tensorboard --logdir "./regressionlogs/fit/" --port 6007

ERROR: Failed to launch TensorBoard (exited with 1).

In [ ]:
python -m tensorboard.main --logdir "C:\Users\arjun\Documents\Lang_chain_learning\DeepLearning\ANN model\regressionlogs" --port 6007

In [23]:
test_loss, test_mae = model.evaluate(X_test,y_test)
print(f'Test MAE: {test_mae}')

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50236.9492 - mae: 50236.9492
Test MAE: 50236.94921875

In [24]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.